package transaction;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * TransactionDemo class definition.
 * Generated by the TouchCORE code generator.
 */
public class TransactionDemo {
    
    public void main(String[] args) {
        Configuration configuration = new Configuration();
        configuration = configuration.configure();
        SessionFactory sessionfactory = configuration.buildSessionFactory();
        Session session = sessionfactory.openSession();
        Transaction transaction = session.beginTransaction();
        System.out.println("Demo Code");
        transaction.commit();
        session.close();
        sessionfactory.close();
    }
}
