package persistence1;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * Student class definition.
 * Generated by the TouchCORE code generator.
 */
public class Student {
    
    private int rollNo;
    private String name;
    
    public Student() {
        /* TODO: No message view defined */
    }

    public void setRollNo(int rollNo) {
        this.rollNo = rollNo;
    }

    public int getRollNo() {
        return this.rollNo;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
